estimator:
  pickle: model.pickl

strategy:
  name: gp
  params:
    seeds: 5

search_space:
  learning_rate_init:
    min: 0.01
    max: 0.9
    type: float

  alpha_reg:
    min: 0.00001
    max: 0.001
    type: float

  alpha_grad:
    min: 0.00001
    max: 0.05
    type: float

  alpha_force:
    min: 0.00001
    max: 0.05
    type: float

cv: 3

dataset_loader:
  name: dsv
  params:
    filenames: /mnt/storage/home/sa16246/repositories/trainingNN/training_Aglaia/first_test/data.csv
    usecols: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125 
    y_col: 126

trials:
    uri: sqlite:///osprey-trials.db

